### PR TITLE
Unit 1 Exercise Answers

### PR DESCRIPTION
**Pull request by alokshakya**
started course make an interactive website and solutions to the first unit.

### CODE REVIEW

**Comment by alokshakya** [comment]
What is the project structure. Please tell me what changes i have to do?

**Comment by ummahusla** [comment]
@alokshakya So at the moment, we have a very simple folder structure which I want to keep the same for the whole repository.

* Learn X
  * 01 Blah blah Y
    * 01 Bla bla blah
    * 02 Bla blah blah
    * 03 And so on
  * 02 Foo bar J
    * 01 Bla bla blah
    * 02 Bla blah blah
    * 03 And so on


You can use [**this folder**](https://github.com/ummahusla/Codecademy-Exercise-Answers/tree/master/Language%20Skills/Learn%20Java) as a reference. 

Please let me know if you have any questions.

**Comment by alokshakya** [comment]
now i renamed according to the project structure. I would add more answers to this course in few days.

**Comment by ummahusla** [comment]
@alokshakya Any updates regards to that PR?

**Comment by ummahusla** [comment]
@alokshakya Please update or abandon the PR

**Comment by ummahusla** [comment]
Closed as inactive PR.

**Pull request closed without merging**
