### PR TITLE
Added solutions to Near Me 3

### PR DESCRIPTION
**Pull request by supermajda**

### CODE REVIEW

**Comment by supermajda** [comment]
If I remember correctly code in leaflet.js and leaflet.css was simply copy/pasted from a link provided by codecademy. I copied all folders and files here as it was there. Up to you to change it.

**Comment by ummahusla** [comment]
@supermajda As I've mentioned previously I would like them either to be replaced with cdn links or removed at all. Is it okay for you to do?

**Comment by ummahusla** [comment]
@supermajda Hi, are you planning to update this PR?

**Comment by supermajda** [comment]
Hi,

Yes I do, got busy with work projects - I can get back to it next week.
Sorry for delay.

Majda Puaca
202-460-0984

**Comment by ummahusla** [comment]
@supermajda Any updates here

**Comment by supermajda** [comment]
Close pls

Majda Puaca

**Pull request closed without merging**
