### PR TITLE
Folder renaming

### PR DESCRIPTION
**Pull request by Moulick**

### CODE REVIEW

**Comment by Moulick** [comment]
okay, done.

**Comment by ummahusla** [comment]
Have you deleted the dublicates and renamed folders?

**Comment by ummahusla** [comment]
Thank you!

**Comment by ummahusla** [comment]
@Moulick hi mate, is there a chance you can me a pull request with a hard reset to `434414fb48c82427deddc70e210aeb8bb0269eff` commit

**Comment by Moulick** [comment]
@ummahusla  I got a mail regarding "hard reset to 434414fb48c82427deddc70e210aeb8bb0269eff commit". Can't find it anywhere on the github web interface. What Would you like me to do ?

**Comment by ummahusla** [comment]
Hi @moulick, it's because I've fixed it and deleted the comment in order not to confuse you. Thanks

**Comment by Moulick** [comment]
@ummahusla  oh, okay, No problem

**Pull request merged**
