### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by the-cryptodog**
你好我要加入你

### CODE REVIEW

**Comment by the-cryptodog** [comment]
> 你好我要加入你

Sorry for this wrong message

**Comment by ummahusla** [comment]
@the-cryptodog Can you please explain the purpose of this Pull Request?

**Comment by the-cryptodog** [comment]
@ummahusla Sorry for being misunderstanding with this. It is a wrong pull request and please accept my apologize.

**Comment by ummahusla** [comment]
> @ummahusla Sorry for being misunderstanding with this. It is a wrong pull request and please accept my apologize.

No worries, have a good day.

**Pull request closed without merging**
