### PR TITLE
Windows-Compatibility Fix (This fix will allow for the repository to be cloned)

### PR DESCRIPTION
**Pull request by alexp9982**
Fixed everything so it is able to be cloned

### CODE REVIEW

**Comment by alexp9982** [comment]
Still a ton more errors to fix, I found the main problem with most of them. It's just time-consuming

**Comment by alexp9982** [comment]
UUUUUUUGGGGGGGHHHHH

**Comment by alexp9982** [comment]
FINALLY DONE

**Comment by ummahusla** [comment]
@alexp9982 Thank you! 👍

**Pull request merged**
